### ISSUE TITLE
why diffient stage of FrcnnOutput has different cls_prob and stage 1st has the highest cls_score

### ISSUE THREAD

**Issue by Peng-wei-Yu** [zhaoweicai/cascade-rcnn#13]
I train cascade rcnn on my own dataset and when testing the val data, I find that 1st stage has the highest cls_score to a object, 2nd stage has the lowest cls_score to the same object. for example, testing pinture a.jpg, 1st stage's FrcnnOutput to a person in a.jpg get cls_score 0.9763, 2nd stage's FrcnnOutput to the person in a.jpg get cls_score 0.5624, is that normal?

**Comment by zhaoweicai** [comment]
It is possible that the scores at 2nd stage are lower than that at 1st stage, because the 2nd stage has higher IoU requirement. A single score on a single example can't tell too much. You may need to evaluate on the whole datasets to see the difference across stages.
