### ISSUE TITLE
About the GPU memory when trainning

### ISSUE THREAD

**Issue by wishinger-li** [zhaoweicai/cascade-rcnn#14]
hi 
  thank you for sharing your work!
I have a problem when i trying to train the model.Since I have only one GTX1080 Gpu, it reports "out of memory"error,when i run the train script. I checked the train.prototxt,and i find the batch_size is 1.
So, how can I get it run or what is the lowest GPU memory should i have with which the code can run?

expect your reply,tahnk you.

**Comment by zhaoweicai** [comment]
I can't help when your GPU card doesn't have enough memory. Probably you can start the smallest model, e.g. alexnet/vggnet on VOC dataset.
