### ISSUE TITLE
cannot run train_detection.sh

### ISSUE THREAD

**Issue by GuoxingYan** [zhaoweicai/cascade-rcnn#15]
When I try to run you training script to train a vgg cascade faster rcnn, I encounter a error like this:

I0530 22:20:18.926313 31741 cudnn_conv_layer.cpp:194] Reallocating workspace storage: 786432
I0530 22:20:18.926367 31741 net.cpp:122] Setting up conv1_2
I0530 22:20:18.926391 31741 net.cpp:129] Top shape: 1 64 1000 600 (38400000)
I0530 22:20:18.926401 31741 net.cpp:137] Memory required for data: 468001080
I0530 22:20:18.926450 31741 layer_factory.hpp:77] Creating layer relu1_2
I0530 22:20:18.926482 31741 net.cpp:84] Creating Layer relu1_2
I0530 22:20:18.926501 31741 net.cpp:406] relu1_2 <- conv1_2
I0530 22:20:18.926537 31741 net.cpp:367] relu1_2 -> conv1_2 (in-place)
I0530 22:20:18.926864 31741 net.cpp:122] Setting up relu1_2
I0530 22:20:18.926888 31741 net.cpp:129] Top shape: 1 64 1000 600 (38400000)
I0530 22:20:18.926898 31741 net.cpp:137] Memory required for data: 621601080
I0530 22:20:18.926913 31741 layer_factory.hpp:77] Creating layer pool1
I0530 22:20:18.926946 31741 net.cpp:84] Creating Layer pool1
I0530 22:20:18.926964 31741 net.cpp:406] pool1 <- conv1_2
I0530 22:20:18.927002 31741 net.cpp:380] pool1 -> pool1
    @     0x7f0aea498368  boost::_bi::list7<>::operator()<>()
I0530 22:20:18.927142 31741 net.cpp:122] Setting up pool1
I0530 22:20:18.927165 31741 net.cpp:129] Top shape: 1 64 500 300 (9600000)
I0530 22:20:18.927175 31741 net.cpp:137] Memory required for data: 660001080
I0530 22:20:18.927188 31741 layer_factory.hpp:77] Creating layer conv2_1
I0530 22:20:18.927238 31741 net.cpp:84] Creating Layer conv2_1
I0530 22:20:18.927258 31741 net.cpp:406] conv2_1 <- pool1
I0530 22:20:18.927299 31741 net.cpp:380] conv2_1 -> conv2_1
I0530 22:20:18.930271 31741 cudnn_conv_layer.cpp:194] Reallocating workspace storage: 1572864
    @     0x7f0aea498242  boost::_bi::bind_t<>::operator()()
I0530 22:20:18.931128 31741 net.cpp:122] Setting up conv2_1
I0530 22:20:18.931154 31741 net.cpp:129] Top shape: 1 128 500 300 (19200000)
I0530 22:20:18.931165 31741 net.cpp:137] Memory required for data: 736801080
I0530 22:20:18.931210 31741 layer_factory.hpp:77] Creating layer relu2_1
I0530 22:20:18.931241 31741 net.cpp:84] Creating Layer relu2_1
I0530 22:20:18.931260 31741 net.cpp:406] relu2_1 <- conv2_1
I0530 22:20:18.931291 31741 net.cpp:367] relu2_1 -> conv2_1 (in-place)
I0530 22:20:18.931601 31741 net.cpp:122] Setting up relu2_1
I0530 22:20:18.931622 31741 net.cpp:129] Top shape: 1 128 500 300 (19200000)
I0530 22:20:18.931632 31741 net.cpp:137] Memory required for data: 813601080
I0530 22:20:18.931646 31741 layer_factory.hpp:77] Creating layer conv2_2
I0530 22:20:18.931684 31741 net.cpp:84] Creating Layer conv2_2
I0530 22:20:18.931702 31741 net.cpp:406] conv2_2 <- conv2_1
I0530 22:20:18.931744 31741 net.cpp:380] conv2_2 -> conv2_2
    @     0x7f0aea4981f4  boost::detail::thread_data<>::run()
    @     0x7f0add9e45d5  (unknown)
    @     0x7f0ad85f56ba  start_thread
    @     0x7f0ae81f541d  clone
    @              (nil)  (unknown)

could you give me some advices?

**Comment by GuoxingYan** [comment]
sh vgg-9s-600-rpn-cascade/train_detection.sh

**Comment by zhaoweicai** [comment]
It looks like the problem of data loading? Can you run any example? Or do you setup the datasets well?

**Comment by GuoxingYan** [comment]
thank you
