### ISSUE TITLE
I wonder whether the result of cascade stage 1 has the same result with base

### ISSUE THREAD

**Issue by Peng-wei-Yu** [zhaoweicai/cascade-rcnn#17]
The result of res50-15s-800-fpn-base is same as res50-15s-800-fpn-cascade stage 1 or not, I did train and test on my own datasets and found the result is not same, to my opinion, I think the result of base should be same as stage1 of cascade

**Comment by zhaoweicai** [comment]
The first stage of res50-15s-800-fpn-cascade should be slightly better than res50-15s-800-fpn-base. Please check table 2 in the paper [http://www.svcl.ucsd.edu/publications/conference/2018/cvpr/cascade-rcnn.pdf]

**Comment by Peng-wei-Yu** [comment]
Thank you very much.
