### ISSUE TITLE
What's the shape of input data in test.prototxt

### ISSUE THREAD

**Issue by Peng-wei-Yu** [zhaoweicai/cascade-rcnn#23]
In detection_data_layer.cpp, with train.prototxt and test.prototxt, the shape of top data blob is 1,3,1312,800, but in deploy.prototxt I see input dim is 1,3,800,1312.

**Comment by GuoxingYan** [comment]
deploy.prototxt的作用就是test或者检测的时候用的吧？这个对于run_cascadercnn_coco.m并没有影响。

**Comment by zhaoweicai** [comment]
Caffe will do automatic reshape according to actual input size.
