### ISSUE TITLE
How to predict the class and position of the target in a new image through the trained model

### ISSUE THREAD

**Issue by GuoxingYan** [zhaoweicai/cascade-rcnn#24]
I trained a model by cascade-rcnn/examples/voc/res50-9s-600-rfcn-cascade/train_detection.sh.How can i predict the class and position of the target in a new image through the trained model .

**Comment by pyupcgithub** [comment]
how do you sloved the problem ?

**Comment by foralliance** [comment]
@GuoxingYan 
请问您是如何解决的？？
