### ISSUE TITLE
Why is total positive equal to 0 in many iterations during the training process?

### ISSUE THREAD

**Issue by GuoxingYan** [zhaoweicai/cascade-rcnn#26]
When I was training, batchsize was equal to 1. There was at least one sample in  my own training pictures, but Why is total positive equal to 0 in many iterations during the training process?

![default](https://user-images.githubusercontent.com/32195410/41092433-728e3658-6a7b-11e8-8419-5e59226efb23.png)

![default](https://user-images.githubusercontent.com/32195410/41093239-69a05092-6a7d-11e8-9cc1-2a842f061a1f.png)

**Comment by emmra** [comment]
I meet the same error?have you solved?
there are many params are equal to -1 and can't save the model??
