### ISSUE TITLE
don't remove redundant high IOU boxes in DecodeBBox operator

### ISSUE THREAD

**Issue by LeonJWH** [zhaoweicai/cascade-rcnn#27]
I tried to transplant cascade RCNN to Detectron, I haven't remove redundant high IOU boxes in DecodeBBox operator, the results came out not as expected. Details are as below:

![2018-06-22 5 13 58](https://user-images.githubusercontent.com/17867054/41768762-c330d064-763f-11e8-86c2-27b0bd37ad39.png)

I wonder whether this operation would bring bad effects to the detection performance, can you give me any advice?
 @zhaoweicai

**Comment by GuoxingYan** [comment]
你复现的是哪一个？作者的小tricks还是挺多的。

**Comment by LeonJWH** [comment]
@GuoxingYan I just add **DecodeBBoxOp** and **DIstributeFpnRpnProposalsOp** on Detectron to train MaskRCNN, the results showed above are not reliable, because a lot of details are not implemented, such as **cls_agnostic_bbox_reg** and settings of **lr_mult**. I am training new model now.

**Comment by zhaoweicai** [comment]
Whether removing high IOU boxes won't have significant differences. We have Detectron version of cascade r-cnn. The results are very consistent even for very high baselines. The Detectron-Cascade-RCNN code will be released later.

**Comment by LeonJWH** [comment]
Thank you ! Very looking forward to your later release

**Comment by LeonJWH** [comment]
Thank you very much! Looking forward to your later release @zhaoweicai

**Comment by LeonJWH** [comment]
@GuoxingYan 能加微信吗

**Comment by LeonJWH** [comment]
@zhaoweicai I noticed that the AP of my first stage are much lower than those of baseline, and the AP of low IOU threshold stay low alone with  stage2 and stage3, what possible reasons may results in this? Can you help me out?
