### ISSUE TITLE
Why no BatchNorm layer is inserted before Scale layer?

### ISSUE THREAD

**Issue by HiKapok** [zhaoweicai/cascade-rcnn#29]
It seems that you didn't do normalization before scale the feature map, like [here](https://github.com/zhaoweicai/cascade-rcnn/blob/187d6a1b2ec7c250e41f8111ee80689084af307e/examples/coco/res50-12s-600-rfcn-cascade/train.prototxt#L886), so what's happening here?

**Comment by zhaoweicai** [comment]
Please have a look at #2 of the section of ``Training Cascade-RCNN``.
