### ISSUE TITLE
Did you try to cascaded with OHEM or just use OHEM in the third stage?

### ISSUE THREAD

**Issue by HiKapok** [zhaoweicai/cascade-rcnn#32]
OHEM is useful in my experiment, did you try to combine OHEM with cascaded rcnn？ should I apply OHEM in every stage of rcnn?

**Comment by zhaoweicai** [comment]
I didn't try OHEM. It is orthogonal. Let me know if you find OHEM works in cascade rcnn.

**Comment by HiKapok** [comment]
@zhaoweicai ok, thanks for you reply

**Comment by yaoqi-zd** [comment]
@HiKapok Hi, did you try OHEM with cascade rcnn, did OHEM bring any performance gain?

**Comment by HiKapok** [comment]
@yaoqi-zd no, it's worser with OHEM, I have tried to apply OHEM in the third stage or in all three stage, the former is better, but still worser than the one without OHEM

**Comment by yaoqi-zd** [comment]
@HiKapok 
I have tried to apply OHEM only in the first stage, 
dataset: kitti 2d detection
classes: car, pedestrian and cyclist
ohem param:
    rois_per_img: 256
performance is sligted better on easy samples but the same on moderate and hard samples.

**Comment by HiKapok** [comment]
@yaoqi-zd thank you for your information. I did get any positive results on my dataset when OHEM is applied.
