### ISSUE TITLE
Confusion about parameter settings in ProposalTarget layer

### ISSUE THREAD

**Issue by yaoqi-zd** [zhaoweicai/cascade-rcnn#35]
In the train.prototxt, what are the two parameters: "img_width" and "img_height" used for? do I need to change them according to my own dataset( like KITTI object detection task, the images are ~375x1240) ?

```
proposal_target_param {
    cls_num: 81
    batch_size: 512
    fg_fraction: 0.25
    num_img_per_batch: 4
    fg_thr: 0.5
    bg_thr_hg: 0.5
    bg_thr_lw: 0.0
    img_width: 600
    img_height: 600
  }
```

Thanks in advance!

**Comment by Cogito2012** [comment]
@yaoqi-zd You can find the usage of these params in `proposal_target_layer.cpp` at [line232](https://github.com/zhaoweicai/cascade-rcnn/blob/187d6a1b2ec7c250e41f8111ee80689084af307e/src/caffe/layers/proposal_target_layer.cpp#L232)

In this while loop, I think these params are used for generating random bg boxes within certain range, only if the sampled bg+fg boxes set is empty (num_keep_rois==0)

**Comment by yaoqi-zd** [comment]
@Cogito2012 Hi, I will check the source code, Thanks very much!
