### ISSUE TITLE
test caffe_model failed 

### ISSUE THREAD

**Issue by zhaowujie** [zhaoweicai/cascade-rcnn#61]
when I trained the model with my data, I tested the model but there is a problem 
*** Aborted at 1539001101 (unix time) try "date -d @1539001101" if you are using GNU date ***
PC: @     0x7f2901cb3ee9 caffe::DetectionEvaluateLayer<>::Forward_cpu()
*** SIGSEGV (@0x0) received by PID 14753 (TID 0x7f29024bb740) from PID 0; stack trace: ***
    @     0x7f28ffd234b0 (unknown)
    @     0x7f2901cb3ee9 caffe::DetectionEvaluateLayer<>::Forward_cpu()
    @     0x7f2901becec7 caffe::Net<>::ForwardFromTo()
    @     0x7f2901bed257 caffe::Net<>::Forward()
    @           0x40bb01 testDetection()
    @           0x408bab main
    @     0x7f28ffd0e830 __libc_start_main
    @           0x409589 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)
can you please answer my issue ASAP, thank you!

**Comment by zhaowujie** [comment]
anyone has the same problem?

**Comment by TinaLiuCV** [comment]
@zhaowujie did you solve the problem? I am using my own dataset to run the testing and encounter with the same problem.

**Comment by zhaoweicai** [comment]
@zhaowujie @TinaLiuCV Does this problem happens when you run the default script for VOC/COCO? For you own dataset, have you provided the window_file as the the format I provided? Actually, this ``DetectionEvaluateLayer`` is just for evaluation. For simplicity, you can just remove it.

**Comment by TinaLiuCV** [comment]
@zhaoweicai It is for my own dataset. The problem is no longer exist after I remodify the test.prototxt. I guess some mistakes are made when I changes the parameters for the anchor boxes.

**Comment by zhaowujie** [comment]
Thanks a lot ～ @TinaLiuCV @zhaoweicai
