### ISSUE TITLE
some problems when training on wider face dataset

### ISSUE THREAD

**Issue by 1700127** [zhaoweicai/cascade-rcnn#71]
![2018-12-20 20-59-39](https://user-images.githubusercontent.com/43924063/50286515-8f782080-049a-11e9-853c-fcbea8807c15.png)
作者你好@zhaoweicai ,请问下你知道这个问题是什么原因吗，谢谢

**Comment by zhaoweicai** [comment]
The positive labels should >0. The background label is 0.
