### ISSUE TITLE
Versions about CUDA,CUDNN,GCC and matlab

### ISSUE THREAD

**Issue by lclin-china** [zhaoweicai/cascade-rcnn#72]
When using CUDA=9.0,CUDNN=7.4,GCC=5.4,matlabR2018a, I got some errors in make matcaffe, can you tell me what are the version of yours?

**Comment by zhaoweicai** [comment]
The version we used was around 07/2017, close to Caffe V1.0. For now, CUDA 8.0 with cuDNN 6.0.20 has been tested.
