### ISSUE TITLE
about regression targets

### ISSUE THREAD

**Issue by LeonJWH** [zhaoweicai/cascade-rcnn#8]
In your code，the regression targets of rcnn is （dx，dy，dw，dh），but in your evaluation script，it seems like that you just take out the outputs from bbox_pred_1st/2nd/3rd layers and use them as the four locations （x1，y1，x2，y2）of rois，can you explain this for me？

**Comment by zhaoweicai** [comment]
You can have a look at the ``deploy.prototxt``. All (dx, dy, dw, dh) have been decoded as (x1, y1, x2, y2) as final output.

**Comment by LeonJWH** [comment]
Got it, thank you very much.

**Comment by LeonJWH** [comment]
Hi, is me again. In your **decode_bbox_layer.cpp**, you screen out rois with high iou, then you add gt_bboxes as rois in proposal_target_layer, what is this for? Can you explain this for me?

**Comment by zhaoweicai** [comment]
It is just to remove redundant gt boxes, since gt boxes will be added in proposal_target_layer each time.

**Comment by LeonJWH** [comment]
OK, thanks a lot.

In addition, the channel of bbox_pred in rcnn is 8, I think is fg/bg delta for each roi, but not num_classes*4. Why did you do like this, does this bring benefits for bbox regression in your experiments?

**Comment by zhaoweicai** [comment]
It is class-agnostic bbox regression. In my experiments, I don't find it has difference with class-specific bbox regression.
