### ISSUE TITLE
inference process

### ISSUE THREAD

**Issue by YangBowenn** [zhaoweicai/cascade-rcnn#83]
在training时，会通过IoU过滤掉前一个级联的部分数据，但在inference时上一步的结果会直接传到下一步，是这样吗？或者是否有其他操作在两个级联网络之间？

**Comment by zhaoweicai** [comment]
During training, the iou threshold will determine the labels (+/-) for the training samples, but no sample will be rejected in the cascade. At inference, all samples will be forwarded to the next step from the previous step. No operations between two steps. Please check the paper for detail.
