### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "box_group_output_param".

### ISSUE THREAD

**Issue by Eloring** [zhaoweicai/cascade-rcnn#85]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RHEL 7.6
- TensorFlow version (use command below):1.14
- Python version: 2.7.16 :: Anaconda, Inc.
- Caffe version: 1.0.0

**Issue**
I downloaded a pre-trained model: [coco-res50-15s-800-fpn-cascade-pretrained.zip](http://www.svcl.ucsd.edu/projects/cascade-rcnn/coco-res50-15s-800-fpn-cascade-pretrained.zip)
I got a same issue during both (1) Inference with TensorRT optimizer and (2) Converting the model to Tensorflow .pb :  "LayerParameter" has no field named "box_group_output_param".

Here are logs:

(1) Inference with TensorRT optimizer

~~~
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 2472:26: Message type "ditcaffe.LayerParameter" has no field named "box_group_output_param".
[TensorRT] ERROR: CaffeParser: Could not parse deploy file
~~~

(2) Converting the model to Tensorflow

~~~
google.protobuf.text_format.ParseError: 2472:3 : Message type "caffe.LayerParameter" has no field named "box_group_output_param".
~~~

Any help would be grateful!

**Comment by zhaoweicai** [comment]
The model was trained on Caffe. If you want to use Caffe2 model, find it here https://github.com/zhaoweicai/Detectron-Cascade-RCNN. If you want to use Cascade R-CNN in TensorFlow, you may try https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN.

**Comment by Eloring** [comment]
@zhaoweicai 
Thanks!

How to do inference using your pre-trained model (without any conversion)? I always got this issue: 
`[libprotobuf ERROR google/protobuf/text_format.cc:312] Error parsing text-format caffe.NetParameter: 2472:26: Message type "caffe.LayerParameter" has no field named "box_group_output_param".`
